routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Route::get('login/google', 'Auth\GoogleController@redirectToGoogle');
Route::get('auth/google/callback', 'Auth\GoogleController@handleGoogleCallback');

Route::get('/staff/print', 'PdfController@printStaff')->name('staff-print');

Route::middleware(['auth'])
    ->group(function () {
    Route::resource('staff', 'StaffController');
    Route::resource('project', 'ProjectController');
    Route::resource('department', 'DepartmentController');
    Route::resource('letter', 'LetterController');
    Route::resource('kwitansi', 'KwitansiController');
    Route::resource('eksternal', 'SuratEksternalController');
    Route::resource('pengumuman', 'PengumumanController');
    Route::resource('peringatan', 'SuratPeringatanController');
    Route::resource('keterangan', 'SuratKeteranganController');
    
    });

Route::get('/logged-in-devices', 'LoggedInDeviceManager@index')
    ->name('logged-in-devices.list')
    ->middleware('auth');

Route::get('/logout/all', 'LoggedInDeviceManager@logoutAllDevices')
    ->name('logged-in-devices.logoutAll')
    ->middleware('auth');

Route::get('/logout/{device_id}', 'LoggedInDeviceManager@logoutDevice')
    ->name('logged-in-devices.logoutSpecific')
    ->middleware('auth');

Auth::routes();

resources/views/pages/eksternal/create.blade.php
@extends('layouts.admin')

@section('title')
    Tambah Data Invoice - Asta HR
@endsection

@push('addon-style')
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.23/sl-1.3.1/datatables.min.css" />
@endpush

@section('content')
    <!--begin::Content-->
    <div class="content d-flex flex-column flex-column-fluid" id="kt_content">

        <div class="subheader py-2 py-lg-4 subheader-solid" id="kt_subheader">
            <div class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
                <div class="d-flex align-items-center flex-wrap mr-1">
                    <div data-aos="zoom-in" class="d-flex align-items-baseline mr-5">
                        <ul class="breadcrumb breadcrumb-transparent font-weight-200 breadcrumb-dot p-0 my-2 font-size-sm">
                            <li class="breadcrumb-item">
                                <a href="" class="text-muted">Home</a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="" class="text-muted">Tambah Data Surat</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="d-flex flex-column-fluid">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card card-custom card-stretch gutter-b">
                            <div class="card-header">
                                <h3 class="card-title font-weight-bolder text-dark">Tambah Data Invoice</h3>
                            </div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-12">
                                        @if ($errors->any())
                                            <div class="alert alert-danger">
                                                <ul>
                                                    @foreach ($errors->all() as $error)
                                                        <li>{{ $error }}</li>
                                                    @endforeach
                                                </ul>
                                            </div>
                                        @endif
                                        <form action="{{ route('letter.store') }}" method="post"
                                            enctype="multipart/form-data">
                                            @csrf

                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        @php
                                                            $month = Carbon\Carbon::now();
                                                        @endphp
                                                        <label>Nomor Surat</label>
                                                        <input type="text" class="form-control form-control-solid text-muted"
                                                        name="nomor" value="1.0{{ $nomorSurat }}/ASTA/INV/{{ $month->month }}/{{ date('Y') }}" autocomplete readonly/>
                                                        
                                                    </input>

                                                    </div>
                                                    <div class="form-group">
                                                        <label>Tujuan</label>
                                                        <input type="text" class="form-control form-control-solid"
                                                            name="tujuan" autocomplete />
                                                    </div>
                                                    <div class="form-group">
                                                        <label for="exampleTextarea">Deskripsi</label>
                                                        <textarea class="form-control form-control-solid" rows="3"
                                                            name="deskripsi" required></textarea>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col text-right">
                                                    <button type="submit" class="btn btn-success px-5 mr-2">
                                                        Simpan
                                                    </button>
                                                    <a type="reset" href="{{ route('letter.index') }}" class="btn btn-default px-6">
                                                        Batal
                                                    </a>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/eksternal/edit.blade.php
@extends('layouts.admin')

@section('title')
    Ubah Data Invoice - Asta HR
@endsection

@section('content')
    <!--begin::Content-->
    <div class="content d-flex flex-column flex-column-fluid" id="kt_content">

        <div class="subheader py-2 py-lg-4 subheader-solid" id="kt_subheader">
            <div class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
                <div class="d-flex align-items-center flex-wrap mr-1">
                    <div data-aos="zoom-in" class="d-flex align-items-baseline mr-5">
                        <ul class="breadcrumb breadcrumb-transparent font-weight-200 breadcrumb-dot p-0 my-2 font-size-sm">
                            <li class="breadcrumb-item">
                                <a href="" class="text-muted">Home</a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="" class="text-muted">Ubah Data Invoice</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="d-flex flex-column-fluid">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card card-custom card-stretch gutter-b">
                            <div class="card-header">
                                <h3 class="card-title font-weight-bolder text-dark">Ubah Data Invoice</h3>
                            </div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-12">
                                        @if ($errors->any())
                                            <div class="alert alert-danger">
                                                <ul>
                                                    @foreach ($errors->all() as $error)
                                                        <li>{{ $error }}</li>
                                                    @endforeach
                                                </ul>
                                            </div>
                                        @endif
                                        <form action="{{ route('letter.update', $item->id) }}" method="POST"
                                            enctype="multipart/form-data">
                                            @method('PUT')
                                            @csrf

                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        @php
                                                            $month = Carbon\Carbon::now();
                                                        @endphp
                                                        <label>Nomor Surat</label>
                                                        <input type="text" class="form-control form-control-solid text-muted"
                                                        name="nomor" value="1.0{{ $item->nomor }}/ASTA/INV/{{ $month->month }}/{{ date('Y') }}" autocomplete readonly/>
                                                        
                                                    </input>

                                                    </div>
                                                    <div class="form-group">
                                                        <label>Tujuan</label>
                                                        <input type="text" class="form-control form-control-solid"
                                                            name="tujuan" value="{{ $item->tujuan }}" autocomplete />
                                                    </div>
                                                    <div class="form-group">
                                                        <label for="exampleTextarea">Deskripsi</label>
                                                        <textarea class="form-control form-control-solid" rows="3"
                                                            name="deskripsi" required>{{ $item->deskripsi }}</textarea>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col text-right">
                                                    <button type="submit" class="btn btn-success px-5 mr-2">
                                                        Simpan
                                                    </button>
                                                    <a type="reset" href="{{ route('letter.index') }}" class="btn btn-default px-6">
                                                        Batal
                                                    </a>
                                                    
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/eksternal/index.blade.php
@extends('layouts.admin')

@section('title')
    Data Surat Eksternal - Asta HR
@endsection

@push('addon-style')
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.23/sl-1.3.1/datatables.min.css"/>
@endpush

@section('content')

<!--begin::Content-->
<div class="content d-flex flex-column flex-column-fluid" id="kt_content">

    <div class="subheader py-2 py-lg-4 subheader-solid" id="kt_subheader">
        <div class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
            <div class="d-flex align-items-center flex-wrap mr-1">
                <div data-aos="zoom-in" class="d-flex align-items-baseline mr-5">
                    <ul class="breadcrumb breadcrumb-transparent font-weight-200 breadcrumb-dot p-0 my-2 font-size-sm">
                        <li class="breadcrumb-item">
                            <a href="" class="text-muted">Home</a>
                        </li>
                        <li class="breadcrumb-item">
                            <a href="" class="text-muted">Data Surat Eksternal</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    

    <div class="d-flex flex-column-fluid">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card card-custom card-stretch gutter-b">
                        <div class="card-header border-0">
                            <h3 class="card-title font-weight-bolder text-dark">Data Surat Eksternal</h3>
                            <div class="card-toolbar">
                                <a href="{{ route('kwitansi.create') }}" type="button" class="btn btn-sm btn-shadow btn-success mr-2">
                                    <i class="flaticon2-plus icon-sm"></i>
                                    Tambah Data
                                </a>
                                <div class="dropdown dropdown-inline" data-toggle="tooltip" title="" data-placement="left" data-original-title="Quick actions">
                                    <a href="#" class="btn btn-clean btn-hover-light-primary btn-sm btn-icon" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="ki ki-bold-more-ver"></i>
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-md dropdown-menu-right">
                                        <!--begin::Navigation-->
                                        <ul class="navi navi-hover">
                                            <li class="navi-item">
                                                <a href="#" class="navi-link">
                                                    <span class="navi-icon">
                                                        <i class="flaticon2-drop"></i>
                                                    </span>
                                                    <span class="navi-text">Ekspor Data PDF</span>
                                                </a>
                                            </li>
                                            <li class="navi-item">
                                                <a href="#" class="navi-link">
                                                    <span class="navi-icon">
                                                        <i class="flaticon2-list-3"></i>
                                                    </span>
                                                    <span class="navi-text">Ekspor Data XLS</span>
                                                </a>
                                            </li>
                                            <li class="navi-item">
                                                <a href="#" class="navi-link">
                                                    <span class="navi-icon">
                                                        <i class="flaticon2-rocket-1"></i>
                                                    </span>
                                                    <span class="navi-text">Impor Data</span>
                                                    <span class="navi-link-badge">
                                                        <span class="label label-light-primary label-inline font-weight-bold">new</span>
                                                    </span>
                                                </a>
                                            </li>
                                            <li class="navi-item">
                                                <a href="{{ route('invoice-print') }}" class="navi-link">
                                                    <span class="navi-icon">
                                                        <i class="flaticon2-bell-2"></i>
                                                    </span>
                                                    <span class="navi-text">Cetak</span>
                                                </a>
                                            </li>
                                            
                                            <li class="navi-separator"></li>
                                            <li class="navi-item pt-2">
                                                <a href="#" class="navi-link">
                                                    <span class="navi-icon">
                                                        <i class="flaticon2-magnifier-tool"></i>
                                                    </span>
                                                    <span class="navi-text">Bantuan</span>
                                                </a>
                                            </li>
                                            
                                        </ul>
                                        <!--end::Navigation-->
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-hover" id="crudTable">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Nomor</th>
                                        <th>Tujuan</th>
                                        <th>Perihal</th>
                                        <th>Pengirim</th>
                                        <th>Aksi</th>
                                    </tr>
                                    </thead>
                                    <tbody></tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>                
            </div>
        </div>
    </div>

</div>
<!--end::Content-->
@endsection

@push('addon-script')
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.23/sl-1.3.1/datatables.min.js"></script>
    <script>
        // AJAX DataTable
        var datatable = $('#crudTable').DataTable({
            // processing: true,
            serverSide: true,
            ordering: true,
            ajax: {
                url: '{!! url()->current() !!}',
            },
            columns: [
                { data: 'id', name: 'id' },
                { data: 'nomor', name: 'nomor' },
                { data: 'tujuan', name: 'tujuan' },
                { data: 'deskripsi', name: 'deskripsi' },
                { data: 'user.name', name: 'user.name' },

                {
                    data: 'action',
                    name: 'action',
                    orderable: false,
                    searchable: false,
                    width: '7%'
                },
            ]
        });
    </script>
@endpush